# This is a basic workflow to help you get started with Actions

name: Monitor Site Status v1

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* */12 * * *'

  # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ dev ]
#   pull_request:
#     branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  msite_job_1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: harry97/mcloud-toolkit:latest
      env:
        SLACK_CLI_TOKEN: ${{ secrets.DEFAULT_SLACK_TOKEN }}
        MT_0001_SLACK_CLI_TOKEN: ${{ secrets.DEFAULT_SLACK_TOKEN }}
        SENDGRID_API_KEY: ${{ secrets.DEFAULT_SENDGRID_TOKEN }}
        EMAIL_FROM: mcloudautomation@gmail.com
        EMAIL_MODE: SENDGRID
        REPLY_EMAIL_ADDRESS: 'Harry <HarryTheDevOpsGuy@gmail.com>'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: HarryTheDevOpsGuy/mConfigs
          token: ${{ secrets.GH_PERSONAL_TOKEN }}

      # Check SSL certs
      - name: Check Website Status
        run: |
          chmod +x "${GITHUB_WORKSPACE}/msite/msite"
          ./msite/msite -e harrythedevopsguy@gmail.com -m 3 -s '#devops'  bp.blogspot.com bbc.co.uk amazon.com t.me uol.com.br feedburner.com imdb.com forbes.com fr.wikipedia.org google.co.jp dropbox.com mail.google.com mail.ru brandbucket.com w3.org creativecommons.org slideshare.net www.yahoo.com msn.com issuu.com 
          ls -la /tmp/

      
          
