# This is a basic workflow to help you get started with Actions

name: Monitor Site Status

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/50 * * * *'

  # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ dev ]
#   pull_request:
#     branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  msite_job_1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: harry97/mcloud-toolkit:latest
      env:
        SLACK_CLI_TOKEN: ${{ secrets.DEFAULT_SLACK_TOKEN }}
        MT_0001_SLACK_CLI_TOKEN: ${{ secrets.DEFAULT_SLACK_TOKEN }}
        SENDGRID_API_KEY: ${{ secrets.DEFAULT_SENDGRID_TOKEN }}
        EMAIL_FROM: mcloudautomation@gmail.com
        EMAIL_MODE: SENDGRID
        REPLY_EMAIL_ADDRESS: 'Harry <HarryTheDevOpsGuy@gmail.com>'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: HarryTheDevOpsGuy/mConfigs
          token: ${{ secrets.GH_PERSONAL_TOKEN }}

      # Check SSL certs
      - name: Check Cert expiry
        run: |
          chmod +x "${GITHUB_WORKSPACE}/msite/msite"
          ./msite/msite -e harrythedevopsguy@gmail.com -s '#devops' www.google.com youtube.com apple.com cloudflare.com microsoft.com www.blogger.com support.google.com play.google.com wordpress.org mozilla.org docs.google.com linkedin.com en.wikipedia.org youtu.be maps.google.com europa.eu adobe.com vimeo.com drive.google.com plus.google.com googleusercontent.com accounts.google.com sites.google.com vk.com cnn.com github.com facebook.com istockphoto.com pt.wikipedia.org bp.blogspot.com bbc.co.uk amazon.com t.me uol.com.br feedburner.com imdb.com forbes.com fr.wikipedia.org google.co.jp dropbox.com mail.google.com mail.ru brandbucket.com w3.org creativecommons.org slideshare.net www.yahoo.com msn.com issuu.com wikimedia.org myspace.com paypal.com reuters.com news.google.com theguardian.com opera.com whatsapp.com bbc.com gstatic.com dailymotion.com google.es medium.com www.weebly.com google.com.br google.de live.com nih.gov abril.com.br developers.google.com line.me get.google.com globo.com policies.google.com jimdofree.com hugedomains.com es.wikipedia.org nytimes.com de.wikipedia.org amazon.co.uk google.fr un.org id.wikipedia.org amazon.co.jp www.gov.uk fandom.com google.it google.pl cdc.gov elpais.com huffingtonpost.com wsj.com dailymail.co.uk android.com change.org apache.org twitter.com books.google.com photos.google.com time.com cpanel.com independent.co.uk aboutads.info telegram.me aliexpress.com draft.blogger.com washingtonpost.com rakuten.co.jp it.wikipedia.org usatoday.com scribd.com tools.google.com buydomains.com samsung.com youronlinechoices.com news.yahoo.com ok.ru office.com tinyurl.com bloomberg.com files.wordpress.com wired.com harvard.edu mediafire.com bit.ly steampowered.com nasa.gov latimes.com booking.com myaccount.google.com translate.google.com search.google.com google.co.uk ig.com.br fb.com thesun.co.uk who.int businessinsider.com ebay.com hatena.ne.jp aol.com dan.com wikia.com archive.org cnet.com gravatar.com google.ru marketingplatform.google.com wa.me goo.gl foxnews.com abcnews.go.com telegraph.co.uk 4shared.com cpanel.net networkadvertising.org huffpost.com terra.com.br plesk.com pinterest.com namecheap.com picasaweb.google.com amazon.de smh.com.au about.com yelp.com forms.gle amazon.fr discord.gg www.wix.com indiatimes.com greenpeace.org nginx.com cbsnews.com gnu.org twitch.tv rambler.ru google.ca trustpilot.com biglobe.ne.jp ria.ru cbc.ca engadget.com spotify.com enable-javascript.com guardian.co.uk sciencedirect.com lemonde.fr stanford.edu mit.edu t.co wikihow.com nginx.org hollywoodreporter.com clickbank.net eventbrite.com imageshack.us xbox.com disney.com shopify.com spiegel.de mashable.com google.co.id addthis.com yadi.sk berkeley.edu naver.com hm.com doubleclick.net icann.org www.over-blog.com mirror.co.uk welt.de fda.gov espn.com ziddu.com sedo.com ibm.com afternic.com newsweek.com ja.wikipedia.org ru.wikipedia.org express.co.uk nationalgeographic.com abc.net.au ign.com pl.wikipedia.org mysql.com walmart.com asus.com economist.com wiley.com academia.edu netvibes.com huawei.com akamaihd.net bandcamp.com instructables.com ovh.co.uk webmd.com m.wikipedia.org orange.fr sciencedaily.com deezer.com whitehouse.gov depositfiles.com nokia.com groups.google.com ovh.com sapo.pt arxiv.org washington.edu digg.com surveymonkey.com sputniknews.com playstation.com google.co.in bp2.blogger.com wp.com alibaba.com detik.com ted.com adssettings.google.com list-manage.com noaa.gov google.com.tw elmundo.es mozilla.com bitly.com rottentomatoes.com nypost.com discord.com pbs.org weibo.com target.com psychologytoday.com ca.gov stackoverflow.com gizmodo.com quora.com nydailynews.com sciencemag.org soundcloud.com mega.nz researchgate.net

  msite_job_2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: harry97/mcloud-toolkit:latest
      env:
        SLACK_CLI_TOKEN: ${{ secrets.DEFAULT_SLACK_TOKEN }}
        MT_0001_SLACK_CLI_TOKEN: ${{ secrets.DEFAULT_SLACK_TOKEN }}
        SENDGRID_API_KEY: ${{ secrets.DEFAULT_SENDGRID_TOKEN }}
        EMAIL_FROM: mcloudautomation@gmail.com
        EMAIL_MODE: SENDGRID
        REPLY_EMAIL_ADDRESS: 'Harry <HarryTheDevOpsGuy@gmail.com>'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: HarryTheDevOpsGuy/mConfigs
          token: ${{ secrets.GH_PERSONAL_TOKEN }}

      # Check SSL certs
      - name: Check Website Status
        run: |
          chmod +x "${GITHUB_WORKSPACE}/msite/msite"
          ./msite/msite -e harrythedevopsguy@gmail.com -s '#devops' instagram.com cnil.fr rt.com sfgate.com code.google.com oup.com addtoany.com nature.com amazon.es cnbc.com godaddy.com dw.com ietf.org yandex.ru shutterstock.com pixabay.com theatlantic.com hp.com lefigaro.fr sendspace.com secureserver.net ggpht.com abc.es nbcnews.com privacyshield.gov ytimg.com picasa.google.com alexa.com tripadvisor.com unesco.org ft.com e-monsite.com finance.yahoo.com oracle.com themeforest.net www.wikipedia.org chicagotribune.com bing.com goodreads.com gofundme.com cornell.edu umich.edu home.neustar techcrunch.com metro.co.uk nikkei.com bloglovin.com allaboutcookies.org theverge.com urbandictionary.com cambridge.org ea.com my.yahoo.com box.com netflix.com buzzfeed.com google.nl britannica.com ipv4.google.com news.com.au yahoo.co.jp ikea.com qq.com columbia.edu gmail.com variety.com disqus.com thetimes.co.uk storage.googleapis.com zendesk.com kickstarter.com googleblog.com lycos.com rapidshare.com npr.org php.net photobucket.com loc.gov www.livejournal.com pinterest.co.uk soratemplates.com state.gov bp0.blogger.com ameblo.jp sina.com.cn www.canalblog.com coursera.org evernote.com imgur.com example.com upenn.edu about.me steamcommunity.com mixcloud.com thedailybeast.com foursquare.com utexas.edu amzn.to salon.com megaupload.com calendar.google.com irs.gov adweek.com weforum.org statista.com dreamstime.com wn.com vkontakte.ru newyorker.com channel4.com epa.gov ehow.com nicovideo.jp dreniq.com ed.gov tes.com cia.gov bp3.blogger.com dell.com dot.tk politico.com plos.org ox.ac.uk elsevier.com wisc.edu hindustantimes.com livescience.com xinhuanet.com khanacademy.org yale.edu chinadaily.com.cn eonline.com skype.com iubenda.com businessinsider.com.au snapchat.com sports.yahoo.com cisco.com 20minutos.es ap.org a8.net springer.com inc.com prestashop.com vox.com newscientist.com orkut.com.br w3schools.com xing.com prezi.com amazon.it offset.com ovh.net viglink.com usgs.gov nhk.or.jp storage.canalblog.com eff.org dribbble.com search.yahoo.com amazon.ca arstechnica.com nifty.com theglobeandmail.com standard.co.uk marriott.com bund.de histats.com fifa.com thehill.com imageshack.com zoom.us repubblica.it so-net.ne.jp mystrikingly.com techradar.com house.gov stores.jp redhat.com worldbank.org rollingstone.com merriam-webster.com boston.com asahi.com last.fm 000webhost.com businesswire.com fortune.com e-recht24.de people.com naver.jp pastebin.com ucoz.ru history.com nps.gov udemy.com hbr.org photos1.blogger.com kinja.com jstor.org windows.net gooyaabitemplates.com biblegateway.com venturebeat.com ndtv.com ftc.gov rediff.com bp1.blogger.com com.com scientificamerican.com howstuffworks.com psu.edu pcmag.com answers.yahoo.com nba.com
